Repository scrapinghub/spidermon, pull requests merged in 2019-02, with the labels that each got.

#77 Fix getting started example (AttributeError: 'ItemCountMonitor' object has no attribute 'stats')
  docs/source/getting-started.rst
Labels: Status: Review Needed, Type: Docs

#93 Add tox-travis to simplify matrix
  .travis.yml
Labels: Status: Review Needed

#100 Included jsonschema as required dependency
  setup.py
Labels: Status: Review Needed

#99 Any colour you like
  .travis.yml
  README.rst
  requirements.txt
  setup.py
  tox.ini
Labels: Status: Review Needed

#97 Basic monitors
  docs/source/monitors.rst
  spidermon/contrib/scrapy/monitors.py
  tests/test_monitors.py
Labels: Status: Review Needed, Type: Enhancement

#103 [MRG+1] Add test coverage
  .coveragerc
  README.rst
  requirements.txt
  tox.ini
Labels: Status: Review Needed

#115 Remove a note about jsonschema 3 in beta
  docs/source/item-validation.rst
Labels: Status: Review Needed

#113 Update note about dependencies
  docs/source/installation.rst
Labels: Type: Docs

#112 Fix problem caused by backward incompatible change in jsonschema 3.0.0
  docs/source/item-validation.rst
  requirements.txt
  tests/test_validators_jsonschema.py
Labels: Status: Review Needed
